<a href="https://colab.research.google.com/github/DawonChoi/tensorflow_learningboard/blob/master/tensorflow_learningboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf   
print(tf.__version__)

2.2.0


# 균일 분포 1x1 랜덤데이터(0~1 실수) uniform(shape, min, max)


In [ ]:
rand = tf.random.uniform([1],0,1)
print(rand)

tf.Tensor([0.8801912], shape=(1,), dtype=float32)


# 균일 분포 NxN 랜덤데이터(0~1 실수)

In [ ]:
rand = tf.random.uniform([5,4],0,1)
print(rand)

tf.Tensor(
[[0.5067352  0.6179217  0.42204785 0.0031023 ]
 [0.17437267 0.24598527 0.43649447 0.7950444 ]
 [0.4838469  0.84667933 0.4567809  0.18198526]
 [0.46405017 0.7775221  0.31302488 0.4846034 ]
 [0.18261504 0.22556472 0.40409064 0.5648216 ]], shape=(5, 4), dtype=float32)


# 정규 분포 랜덤데이터 normal(shape, mean, standard deviation)

In [ ]:
normal_rand = tf.random.normal([4], 0, 1)
print(normal_rand)

tf.Tensor([-0.16464928  0.37768605 -1.392089    0.9149462 ], shape=(4,), dtype=float32)


# 시그모이드 함수 구현

In [ ]:
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

x = 1
y = 0
w = tf.random.normal([1],0,1)
output = sigmoid(x * w)
print("실제 출력 :",output)
print(f"에러(기대 출력(0) - 실제 출력) : {y-output}")

실제 출력 : 0.5017388815502476
에러(기대 출력(0) - 실제 출력) : -0.5017388815502476


# 경사 하강법 활용 w = w + 입력 * 학습률 * 에러 (학습률 : w를 업데이트 하는 정도)

In [ ]:
for i in range(5000):
  output = sigmoid(x * w)
  error = y - output
  w = w + x * 0.1 * error

  if i % 100 == 99:
    print(i, error, output)

99 -0.10212199918154194 0.10212199918154194
199 -0.05234654694974143 0.05234654694974143
299 -0.03484493952035447 0.03484493952035447
399 -0.02603318946440947 0.02603318946440947
499 -0.020750476191181855 0.020750476191181855
599 -0.017237849311251406 0.017237849311251406
699 -0.014736123619364515 0.014736123619364515
799 -0.012865098083539963 0.012865098083539963
899 -0.011413630174055271 0.011413630174055271
999 -0.010255162742259244 0.010255162742259244
1099 -0.00930932232939592 0.00930932232939592
1199 -0.008522650044707866 0.008522650044707866
1299 -0.007858145277918043 0.007858145277918043
1399 -0.00728946058446925 0.00728946058446925
1499 -0.006797306204295395 0.006797306204295395
1599 -0.006367204879978169 0.006367204879978169
1699 -0.005988158525637608 0.005988158525637608
1799 -0.005651603285833723 0.005651603285833723
1899 -0.0053507727243645295 0.0053507727243645295
1999 -0.005080290059449737 0.005080290059449737
2099 -0.0048357691662370495 0.0048357691662370495
2199 -0.004

# 입력 0 -> 출력 1 by 경사 하강법

In [ ]:
x = 0
y = 1
w = tf.random.normal([1],0,1)

for i in range(1000):
  output = sigmoid(x * w)
  error = y - output
  w = w + x * 0.1 * error

  if i % 100 == 99:
    print(i, error, output)

99 0.5 0.5
199 0.5 0.5
299 0.5 0.5
399 0.5 0.5
499 0.5 0.5
599 0.5 0.5
699 0.5 0.5
799 0.5 0.5
899 0.5 0.5
999 0.5 0.5


- 출력이 0.5에서 변하지 않는다. 입력이 0 이므로 경사 하강법의 식에따라 1000번의 실행동안 w값은 변하지 않는다

# 편향(const 같은 개념)

In [ ]:
x = 0
y = 1
w = tf.random.normal([1],0,1)

# 편향 b
b = tf.random.normal([1],0,1)

for i in range(1000):
  output = sigmoid(x * w + 1 * b)
  error = y - output
  w = w + x * 0.1 * error
  b = b + 1 * 0.1 * error

  if i % 100 == 99:
    print(i, error, output)

99 0.10752340337073574 0.8924765966292643
199 0.05380889241742415 0.9461911075825759
299 0.035498745628444905 0.9645012543715551
399 0.026399671136648872 0.9736003288633511
499 0.020983916743011144 0.9790160832569889
599 0.017399200654773184 0.9826007993452268
699 0.014854198169924837 0.9851458018300752
799 0.012955182715670088 0.9870448172843299
899 0.011484609462896422 0.9885153905371036
999 0.010312518756825817 0.9896874812431742


# 신경망 네트워크 구현: AND

In [ ]:
import numpy as np
x = np.array([[1,1], [1,0], [0,1], [0,0]])
y = np.array([[1], [0], [0], [0]])
w = tf.random.normal([2],0,1)
b = tf.random.normal([1],0,1)
b_x = 1

for i in range(2000):
  error_sum = 0
  
  for j in range(4):
    output = sigmoid(np.sum(x[j]*w)+b_x*b)
    error = y[j][0] - output
    w = w + x[j] * 0.1 * error
    b = b + b_x * 0.1 * error
    error_sum += error

  if i % 200 == 199:
    print(i, error_sum)

# test of AND network
print('\n테스트')
for i in range(4):
  print('X:',x[i], 'Y:', y[i], 'Output:',sigmoid(np.sum(x[i]*w)+b))

199 -0.11778863455094749
399 -0.06826431436627693
599 -0.047971227788960756
799 -0.03686729632975872
999 -0.02988061660551168
1199 -0.025090442236432066
1399 -0.021606065177641798
1599 -0.018962400631874054
1799 -0.016886546950081006
1999 -0.015217510158226739

테스트
X: [1 1] Y: [1] Output: 0.9644741020182622
X: [1 0] Y: [0] Output: 0.02517286169707915
X: [0 1] Y: [0] Output: 0.025250721509681374
X: [0 0] Y: [0] Output: 2.463937238932992e-05
