<a href="https://colab.research.google.com/github/DawonChoi/tensorflow_learningboard/blob/master/data%20visualization/numpy_skillboard.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

array1 = np.arange(16).reshape(4,4)
print(array1)

#broadcasting
array_add = np.array([0,1,2,3]).reshape(4, 1)
array1 += array_add
print(array1)

#masking
array2 = array1 < 10
print(array2)
array1[array2] = 100
print(array1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]
[[ True  True  True  True]
 [ True  True  True  True]
 [False False False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [ 10  11  12  13]
 [ 15  16  17  18]]
